# Generated by Django 3.2 on 2022-08-12 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_comments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsofusers', to='auctions.auctionlisting'),
        ),
    ]
