# Generated by Django 3.2 on 2022-08-12 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_comments_commentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commentauc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentsofposts', to='auctions.auctionlisting'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsofusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
