# Generated by Django 3.2 on 2022-08-12 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20220812_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waucid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wlofposts', to='auctions.auctionlisting')),
                ('wid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wlsofusers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
