# Generated by Django 3.2 on 2022-08-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='imageupload',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
